// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcvFOqsw7Eo6jBIqNl0y_AGFLqFkRTRys',
    appId: '1:18709322318:web:c205abb5e68a8863b7811f',
    messagingSenderId: '18709322318',
    projectId: 'perhitungan-interior',
    authDomain: 'perhitungan-interior.firebaseapp.com',
    storageBucket: 'perhitungan-interior.firebasestorage.app',
    measurementId: 'G-EJY2RGBVYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6sH3cXBUG_tLAeXEI9a7rC2KxQmehKA',
    appId: '1:18709322318:android:8f209eb7e8440978b7811f',
    messagingSenderId: '18709322318',
    projectId: 'perhitungan-interior',
    storageBucket: 'perhitungan-interior.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7gMVwabRNY-oj5mNzivtQ_zElulP8MQ',
    appId: '1:18709322318:ios:e4f63e9204b19a48b7811f',
    messagingSenderId: '18709322318',
    projectId: 'perhitungan-interior',
    storageBucket: 'perhitungan-interior.firebasestorage.app',
    iosBundleId: 'com.example.ganeshaInterior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi7gMVwabRNY-oj5mNzivtQ_zElulP8MQ',
    appId: '1:18709322318:ios:e4f63e9204b19a48b7811f',
    messagingSenderId: '18709322318',
    projectId: 'perhitungan-interior',
    storageBucket: 'perhitungan-interior.firebasestorage.app',
    iosBundleId: 'com.example.ganeshaInterior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcvFOqsw7Eo6jBIqNl0y_AGFLqFkRTRys',
    appId: '1:18709322318:web:349afdf4a762c367b7811f',
    messagingSenderId: '18709322318',
    projectId: 'perhitungan-interior',
    authDomain: 'perhitungan-interior.firebaseapp.com',
    storageBucket: 'perhitungan-interior.firebasestorage.app',
    measurementId: 'G-PG6DJW2X5S',
  );
}
